import appleAuth from '@invertase/react-native-apple-authentication';
import {useEffect} from 'react';
import useOnyx from '@hooks/useOnyx';
import * as Session from '@userActions/Session';
import ONYXKEYS from '@src/ONYXKEYS';

/**
 * Apple Sign In wrapper for iOS
 * revokes the session if the credential is revoked.
 */
function AppleAuthWrapper() {
    const [credentials] = useOnyx(ONYXKEYS.CREDENTIALS, {canBeMissing: true});
    const [session] = useOnyx(ONYXKEYS.SESSION, {canBeMissing: true});

    useEffect(() => {
        if (!appleAuth.isSupported) {
            return;
        }
        const removeListener = appleAuth.onCredentialRevoked(() => {
            Session.signOut({autoGeneratedLogin: credentials?.autoGeneratedLogin, authToken: session?.authToken});
        });

        return () => {
            removeListener();
        };
    }, [credentials?.autoGeneratedLogin, session?.authToken]);

    return null;
}

export default AppleAuthWrapper;
